# Generated by Django 6.0.1 on 2026-03-14 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('storage_backend', models.CharField(choices=[('ipfs', 'IPFS'), ('s3', 'S3 Vault'), ('encrypted_blob', 'Encrypted Blob Store')], default='ipfs', max_length=16)),
                ('ipfs_cid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('encryption_key_b64', models.TextField(blank=True, help_text="Per-file AES key, itself encrypted with user's Kyber key")),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_attachment',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_mention',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext_b64', models.TextField(help_text='AES-256-GCM encrypted message body')),
                ('nonce_b64', models.CharField(help_text='12-byte GCM nonce, base64', max_length=32)),
                ('auth_tag_b64', models.CharField(help_text='16-byte GCM auth tag, base64', max_length=32)),
                ('kyber_ciphertext_b64', models.TextField(blank=True, help_text='Kyber-1024 encapsulated symmetric key')),
                ('dilithium_signature_b64', models.TextField(blank=True, help_text='Dilithium3 message signature')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('system', 'System'), ('call', 'Call Event')], default='text', max_length=16)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ttl_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds until hard-delete. Null = use channel/workspace policy.', null=True)),
                ('destroy_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_destroyed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'messaging_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_bookmark',
            },
        ),
        migrations.CreateModel(
            name='MessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_ciphertext_b64', models.TextField()),
                ('previous_nonce_b64', models.CharField(max_length=32)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_message_edit',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_message_read',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_code', models.CharField(help_text='Unicode or :custom_name:', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_reaction',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_thread',
                'ordering': ['-last_reply_at'],
            },
        ),
        migrations.CreateModel(
            name='TTLPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('workspace', 'Workspace'), ('channel', 'Channel'), ('message', 'Message')], max_length=16)),
                ('scope_id', models.UUIDField(db_index=True)),
                ('ttl_seconds', models.PositiveIntegerField()),
                ('applies_to_type', models.CharField(choices=[('all', 'All'), ('text', 'Text Only'), ('file', 'Files Only')], default='all', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_ttl_policy',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('token_hash', models.CharField(max_length=256, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messaging_webhook',
            },
        ),
    ]
