# Generated by Django 6.0.1 on 2026-03-14 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_botcommand_messageforward_messagesearchindex_and_more'),
        ('workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_token', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('fraud', 'Fraud'), ('misconduct', 'Misconduct'), ('aml', 'AML Violation'), ('data_breach', 'Data Breach'), ('bribery', 'Bribery'), ('other', 'Other')], max_length=50)),
                ('ciphertext_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('attachments_cid', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_anonymous_report',
            },
        ),
        migrations.CreateModel(
            name='ChannelRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('auto_wipe', models.BooleanField(default=False)),
                ('legal_hold', models.BooleanField(default=False)),
                ('legal_hold_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='workspace.channel')),
                ('legal_hold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_retention_policy',
            },
        ),
        migrations.CreateModel(
            name='SecureVideoCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key_b64', models.TextField()),
                ('dtls_fingerprint', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed')], default='ringing', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('recording_cid', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='workspace.channel')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='video_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_video_call',
            },
        ),
        migrations.CreateModel(
            name='SecureVoiceMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_cid', models.TextField()),
                ('ciphertext_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_transcribed', models.BooleanField(default=False)),
                ('transcript_encrypted_b64', models.TextField(blank=True)),
                ('destroy_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='workspace.channel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_voice_message',
            },
        ),
        migrations.CreateModel(
            name='TradingCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(blank=True, max_length=50)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('direction', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_pre_trade', models.BooleanField(default=False)),
                ('is_post_trade', models.BooleanField(default=False)),
                ('mifid_reported', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_comm', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_trading_comm',
            },
        ),
    ]
