# Generated by Django 6.0.1 on 2026-03-14 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_chatbotsession_notificationqueue_and_more'),
        ('workspace', '0004_servicelevelagreement_workflowinstance_workflowstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRoomDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_cid', models.TextField()),
                ('ciphertext_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_file_room_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('print', 'Print'), ('share', 'Share')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('watermark_id', models.CharField(blank=True, max_length=64)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='messaging.fileroomdocument')),
            ],
            options={
                'db_table': 'messaging_document_access_log',
            },
        ),
        migrations.CreateModel(
            name='PinnedResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('message', 'Message'), ('document', 'Document'), ('link', 'Link'), ('contact', 'Contact'), ('deal', 'Deal'), ('report', 'Report')], max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_resources', to='workspace.channel')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_pinned_resource',
            },
        ),
        migrations.CreateModel(
            name='SecureFileRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('due_diligence', 'Due Diligence'), ('legal', 'Legal Documents'), ('financial', 'Financial Reports'), ('regulatory', 'Regulatory Filing'), ('board', 'Board Documents')], max_length=50)),
                ('watermark_enabled', models.BooleanField(default=True)),
                ('download_enabled', models.BooleanField(default=False)),
                ('print_enabled', models.BooleanField(default=False)),
                ('screenshot_blocked', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='file_rooms', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_rooms', to='workspace.workspace')),
            ],
            options={
                'db_table': 'messaging_file_room',
            },
        ),
        migrations.AddField(
            model_name='fileroomdocument',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='messaging.securefileroom'),
        ),
    ]
