# Generated by Django 6.0.1 on 2026-03-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_remove_messagetemplate_is_shared_and_more'),
        ('workspace', '0017_apikey_appversion_geolocation_knowledgetag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='category',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AlterModelTable(
            name='messagetemplate',
            table='messaging_template',
        ),
    ]
