# Generated by Django 6.0.1 on 2026-03-14 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('alert', 'Security Alert')], default='info', max_length=16)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.CharField(blank=True, max_length=512)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'compliance_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily_audit', 'Daily Audit Summary'), ('user_activity', 'User Activity Report'), ('vault_access', 'Vault Access Report'), ('message_retention', 'Message Retention Report'), ('security_incidents', 'Security Incidents Report'), ('regulatory', 'Regulatory Submission')], max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('report_ipfs_cid', models.CharField(blank=True, help_text='IPFS CID of encrypted PDF report', max_length=128)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_report',
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_retention_days', models.PositiveIntegerField(default=365)),
                ('file_retention_days', models.PositiveIntegerField(default=730)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=2555, help_text='7 years for banking compliance')),
                ('auto_delete_enabled', models.BooleanField(default=True)),
                ('legal_hold', models.BooleanField(default=False, help_text='Freeze all deletions during legal hold')),
                ('legal_hold_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_retention_policy',
            },
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('messages', 'Messages'), ('audit_logs', 'Audit Logs'), ('user_data', 'User Data')], max_length=32)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('export_ipfs_cid', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_export_request',
            },
        ),
        migrations.CreateModel(
            name='ForensicsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_scrubbing', models.BooleanField(default=True, help_text='Remove EXIF and file metadata on upload')),
                ('header_scrubbing', models.BooleanField(default=True, help_text='Strip identifying headers from responses')),
                ('log_retention_wipe', models.BooleanField(default=False, help_text='Wipe server logs after 30 days')),
                ('clipboard_protection', models.BooleanField(default=True)),
                ('screenshot_detection', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_forensics_block',
            },
        ),
        migrations.CreateModel(
            name='RegulatorAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulator_name', models.CharField(max_length=128)),
                ('regulator_email', models.EmailField(max_length=254)),
                ('access_token_hash', models.CharField(max_length=256, unique=True)),
                ('scope', models.JSONField(default=list, help_text='List of accessible resource types')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('access_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_regulator_access',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAIL', 'Failed Login'), ('ACCOUNT_LOCKED', 'Account Locked'), ('MFA_VERIFIED', 'MFA Verified'), ('MFA_FAIL', 'MFA Failure'), ('PASSWORD_CHANGED', 'Password Changed'), ('VAULT_OPENED', 'Vault Session Opened'), ('VAULT_ACCESS_DENIED', 'Vault Access Denied'), ('HW_KEY_REGISTERED', 'Hardware Key Registered'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('DATA_EXPORT', 'Data Export'), ('TTL_WIPE', 'Message TTL Wipe'), ('SESSION_REVOKED', 'Session Revoked'), ('INVALID_SIGNATURE', 'Invalid Message Signature')], db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'compliance_security_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data Processing'), ('message_monitoring', 'Message Monitoring'), ('audit_logging', 'Audit Logging'), ('cross_border_transfer', 'Cross-Border Data Transfer')], max_length=32)),
                ('version', models.CharField(help_text='Policy version e.g. v2.3', max_length=16)),
                ('consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_user_consent',
            },
        ),
    ]
