# Generated by Django 6.0.1 on 2026-03-14 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_systemhealthlog_threatintelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMLAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('structuring', 'Structuring'), ('layering', 'Layering'), ('smurfing', 'Smurfing'), ('rapid_movement', 'Rapid Movement'), ('unusual_pattern', 'Unusual Pattern'), ('pep_match', 'PEP Match'), ('sanctions_match', 'Sanctions Match')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_aml_alert',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ojk_daily', 'OJK Daily'), ('bi_weekly', 'BI Weekly'), ('ppatk_monthly', 'PPATK Monthly'), ('lkd_quarterly', 'LKD Quarterly'), ('swift_annual', 'SWIFT Annual')], max_length=50)),
                ('regulator', models.CharField(max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('total_sar', models.PositiveIntegerField(default=0)),
                ('report_data', models.JSONField(default=dict)),
                ('file_path', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_regulatory_report',
            },
        ),
        migrations.CreateModel(
            name='SARReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('narrative', models.TextField()),
                ('submitted_to', models.CharField(default='PPATK', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_reports', to='compliance.amlalert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_sar_report',
            },
        ),
        migrations.CreateModel(
            name='TransactionMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('payment', 'Payment'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('fx', 'Foreign Exchange'), ('swift', 'SWIFT')], max_length=50)),
                ('sender_account', models.CharField(blank=True, max_length=100)),
                ('receiver_account', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_transaction_monitor',
            },
        ),
        migrations.AddField(
            model_name='amlalert',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_alerts', to='compliance.transactionmonitor'),
        ),
        migrations.AddIndex(
            model_name='transactionmonitor',
            index=models.Index(fields=['user', 'created_at'], name='compliance__user_id_9698d8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmonitor',
            index=models.Index(fields=['is_flagged', 'status'], name='compliance__is_flag_6a7ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmonitor',
            index=models.Index(fields=['risk_score'], name='compliance__risk_sc_1d2679_idx'),
        ),
    ]
