# Generated by Django 6.0.1 on 2026-03-14 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_amlalert_regulatoryreport_sarreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_name', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(choices=[('velocity', 'Velocity Check'), ('geolocation', 'Geolocation Anomaly'), ('device', 'Device Fingerprint'), ('behavioral', 'Behavioral Analysis'), ('network', 'Network Analysis')], max_length=50)),
                ('rules', models.JSONField(default=dict)),
                ('threshold', models.FloatField(default=0.8)),
                ('is_active', models.BooleanField(default=True)),
                ('true_positive_rate', models.FloatField(default=0.0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_fraud_pattern',
            },
        ),
        migrations.CreateModel(
            name='ImmutableAuditChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(default=0, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('actor_id', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('data_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('chain_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
            options={
                'db_table': 'compliance_immutable_chain',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed Fraud'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('evidence', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.transactionmonitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.fraudpattern')),
            ],
            options={
                'db_table': 'compliance_fraud_case',
            },
        ),
        migrations.CreateModel(
            name='KYCVerificationFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('identity', 'Identity Verification'), ('liveness', 'Liveness Check'), ('document', 'Document Scan'), ('address', 'Address Verification'), ('pep_check', 'PEP Screening'), ('sanctions', 'Sanctions Check'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('result_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_kyc_flow',
            },
        ),
        migrations.CreateModel(
            name='PEPScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pep', models.BooleanField(default=False)),
                ('pep_category', models.CharField(blank=True, max_length=50)),
                ('pep_country', models.CharField(blank=True, max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('screened_by', models.CharField(default='automated', max_length=50)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pep_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_pep_screening',
            },
        ),
        migrations.CreateModel(
            name='SanctionsCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('sanctions_list', models.CharField(blank=True, max_length=50)),
                ('match_score', models.FloatField(default=0.0)),
                ('match_details', models.JSONField(default=dict)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('screened_by', models.CharField(default='automated', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_sanctions_check',
            },
        ),
    ]
