# Generated by Django 6.0.1 on 2026-03-14 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_fraudpattern_immutableauditchain_fraudcase_and_more'),
        ('workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=100)),
                ('records_deleted', models.PositiveIntegerField(default=0)),
                ('bytes_freed', models.BigIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('executed_by', models.CharField(default='celery', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_retention_execution',
            },
        ),
        migrations.CreateModel(
            name='NDARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_hash', models.CharField(max_length=64)),
                ('document_cid', models.TextField(blank=True)),
                ('signature_b64', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deal_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ndas', to='workspace.dealroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_nda_record',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulator', models.CharField(choices=[('ojk', 'OJK'), ('bi', 'Bank Indonesia'), ('ppatk', 'PPATK'), ('basel', 'Basel Committee'), ('swift', 'SWIFT'), ('fatf', 'FATF')], max_length=50)),
                ('requirement', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence', models.CharField(blank=True, max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_regulatory_deadline',
            },
        ),
        migrations.CreateModel(
            name='StressTestScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('credit_risk', 'Credit Risk'), ('market_risk', 'Market Risk'), ('liquidity_risk', 'Liquidity Risk'), ('operational_risk', 'Operational Risk'), ('systemic_risk', 'Systemic Risk')], max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('assumptions', models.TextField(blank=True)),
                ('is_regulatory', models.BooleanField(default=False)),
                ('regulator', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_stress_test_scenario',
            },
        ),
        migrations.CreateModel(
            name='StressTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capital_ratio', models.FloatField(default=0.0)),
                ('liquidity_ratio', models.FloatField(default=0.0)),
                ('npv_impact', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('result_data', models.JSONField(default=dict)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.stresstestscenario')),
            ],
            options={
                'db_table': 'compliance_stress_test_result',
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watchlist_type', models.CharField(choices=[('aml', 'AML Watchlist'), ('fraud', 'Fraud Watchlist'), ('sanctions', 'Sanctions List'), ('pep', 'PEP List'), ('internal', 'Internal Watchlist')], max_length=50)),
                ('reason', models.TextField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_additions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_watchlist',
            },
        ),
    ]
