# Generated by Django 6.0.1 on 2026-03-14 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_dataretentionexecution_ndarecord_regulatorydeadline_and_more'),
        ('workspace', '0003_escalationmatrix_tradingdesk_workspaceannouncement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIComplianceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_source', models.CharField(choices=[('nlp_scan', 'NLP Message Scan'), ('behavior_analysis', 'Behavior Analysis'), ('pattern_match', 'Pattern Matching'), ('anomaly_detection', 'Anomaly Detection'), ('sentiment_analysis', 'Sentiment Analysis')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('raw_signal', models.JSONField(default=dict)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_ai_alert',
            },
        ),
        migrations.CreateModel(
            name='CommunicationSurveillance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('keyword', 'Keyword Scan'), ('nlp', 'NLP Analysis'), ('sentiment', 'Sentiment Analysis'), ('insider_trading', 'Insider Trading Detection'), ('market_manipulation', 'Market Manipulation')], max_length=50)),
                ('flagged_keywords', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('messages_scanned', models.PositiveIntegerField(default=0)),
                ('messages_flagged', models.PositiveIntegerField(default=0)),
                ('scan_period_start', models.DateTimeField()),
                ('scan_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_comm_surveillance',
            },
        ),
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('fraud_detection', 'Fraud Detection'), ('aml_detection', 'AML Detection'), ('sentiment', 'Sentiment Analysis'), ('anomaly', 'Anomaly Detection'), ('kyc_verification', 'KYC Verification'), ('risk_scoring', 'Risk Scoring')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('model_hash', models.CharField(max_length=64)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_ml_model',
            },
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_category', models.CharField(choices=[('credit', 'Credit Risk'), ('market', 'Market Risk'), ('liquidity', 'Liquidity Risk'), ('operational', 'Operational Risk'), ('reputational', 'Reputational Risk'), ('compliance', 'Compliance Risk'), ('cyber', 'Cyber Risk'), ('strategic', 'Strategic Risk')], max_length=50)),
                ('risk_name', models.CharField(max_length=255)),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('risk_score', models.FloatField(default=0.0)),
                ('mitigation', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('mitigating', 'Mitigating'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='identified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_risk_matrix',
            },
        ),
    ]
