# Generated by Django 6.0.1 on 2026-03-14 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_aicompliancealert_communicationsurveillance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('hqla_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_cash_outflow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lcr', models.FloatField()),
                ('available_stable_funding', models.DecimalField(decimal_places=2, max_digits=20)),
                ('required_stable_funding', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nsfr', models.FloatField()),
                ('is_compliant', models.BooleanField(default=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_liquidity_report',
            },
        ),
        migrations.CreateModel(
            name='BaselCapitalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('tier1_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tier2_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('risk_weighted_assets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('car_ratio', models.FloatField()),
                ('lcr_ratio', models.FloatField()),
                ('nsfr_ratio', models.FloatField()),
                ('leverage_ratio', models.FloatField()),
                ('is_compliant', models.BooleanField(default=True)),
                ('submitted_to_ojk', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_basel_capital',
            },
        ),
    ]
