# Generated by Django 6.0.1 on 2026-03-14 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_liquidityreport_baselcapitalreport'),
        ('workspace', '0004_servicelevelagreement_workflowinstance_workflowstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('external', 'External Audit'), ('regulatory', 'Regulatory Examination'), ('penetration_test', 'Penetration Test'), ('iso_27001', 'ISO 27001 Audit')], max_length=50)),
                ('finding_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('observation', 'Observation'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                ('recommendation', models.TextField()),
                ('management_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_remediation', 'In Remediation'), ('resolved', 'Resolved'), ('accepted', 'Risk Accepted')], default='open', max_length=20)),
                ('due_date', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_audit_finding',
            },
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('affected_roles', models.JSONField(default=list)),
                ('affected_instruments', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_blackout_period',
            },
        ),
        migrations.CreateModel(
            name='GDPRRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('access', 'Right to Access'), ('erasure', 'Right to Erasure'), ('portability', 'Data Portability'), ('rectification', 'Rectification'), ('restriction', 'Restriction'), ('objection', 'Objection')], max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('response_data_cid', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_gdpr', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_gdpr_request',
            },
        ),
        migrations.CreateModel(
            name='InsiderTradingMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=50)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('short', 'Short'), ('option', 'Option')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('is_during_blackout', models.BooleanField(default=False)),
                ('has_material_info', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_insider', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_insider_trading',
            },
        ),
    ]
