# Generated by Django 6.0.1 on 2026-03-14 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_auditfinding_blackoutperiod_gdprrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberIncidentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('incident_type', models.CharField(choices=[('ransomware', 'Ransomware'), ('data_breach', 'Data Breach'), ('ddos', 'DDoS Attack'), ('apt', 'Advanced Persistent Threat'), ('insider', 'Insider Threat'), ('zero_day', 'Zero Day Exploit'), ('supply_chain', 'Supply Chain Attack')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('affected_systems', models.JSONField(default=list)),
                ('affected_users_count', models.PositiveIntegerField(default=0)),
                ('containment_steps', models.JSONField(default=list)),
                ('eradication_steps', models.JSONField(default=list)),
                ('recovery_steps', models.JSONField(default=list)),
                ('lessons_learned', models.TextField(blank=True)),
                ('reported_to_ojk', models.BooleanField(default=False)),
                ('reported_to_bssn', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('contained', 'Contained'), ('eradicated', 'Eradicated'), ('recovered', 'Recovered'), ('closed', 'Closed')], default='detected', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lead_responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_cyber_incident',
            },
        ),
        migrations.CreateModel(
            name='PrivacyImpactAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('data_types', models.JSONField(default=list)),
                ('processing_purpose', models.TextField()),
                ('legal_basis', models.CharField(max_length=100)),
                ('risks_identified', models.JSONField(default=list)),
                ('mitigations', models.JSONField(default=list)),
                ('residual_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('dpo_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dpias', to=settings.AUTH_USER_MODEL)),
                ('dpo_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_dpia',
            },
        ),
    ]
