# Generated by Django 6.0.1 on 2026-03-15 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_cyberincidentresponse_privacyimpactassessment'),
        ('workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('bug', 'Bug'), ('outage', 'Service Outage'), ('security', 'Security Issue'), ('data_loss', 'Data Loss'), ('performance', 'Performance Issue'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents_rw', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_incident_report',
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='compliance.incidentreport')),
            ],
            options={
                'db_table': 'compliance_incident_timeline',
            },
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_shifts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_schedules', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_oncall_schedule',
            },
        ),
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_cause', models.TextField()),
                ('impact', models.TextField()),
                ('timeline', models.TextField()),
                ('action_items', models.JSONField(default=list)),
                ('lessons_learned', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_mortem', to='compliance.incidentreport')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_post_mortem',
            },
        ),
        migrations.CreateModel(
            name='RunBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('deployment', 'Deployment'), ('incident', 'Incident Response'), ('onboarding', 'Onboarding'), ('maintenance', 'Maintenance'), ('security', 'Security')], max_length=50)),
                ('steps', models.JSONField(default=list)),
                ('content_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_runbook',
            },
        ),
    ]
