# Generated by Django 6.0.1 on 2026-03-21 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_alertrule_alertinstance_auditexport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('requested_by', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('approver_1', models.CharField(blank=True, max_length=50)),
                ('approver_2', models.CharField(blank=True, max_length=50)),
                ('approved_at', models.DateTimeField(null=True)),
                ('target_user_id', models.CharField(max_length=50)),
                ('access_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_emergency_access',
            },
        ),
        migrations.CreateModel(
            name='ImmutableAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=50)),
                ('sender_id', models.CharField(max_length=50)),
                ('receiver_id', models.CharField(blank=True, max_length=50)),
                ('message_hash', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('device_info', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('chain_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'compliance_immutable_audit',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('general', 'General Chat'), ('official', 'Official Instruction'), ('operational', 'Operational')], default='general', max_length=20)),
                ('allow_self_destruct', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('require_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_channel_policy',
                'unique_together': {('workspace_id', 'channel_name')},
            },
        ),
        migrations.CreateModel(
            name='ShamirKeyShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('share_index', models.PositiveSmallIntegerField()),
                ('share_holder', models.CharField(max_length=100)),
                ('share_holder_id', models.CharField(max_length=50)),
                ('encrypted_share', models.TextField()),
                ('threshold', models.PositiveSmallIntegerField(default=2)),
                ('total_shares', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_shamir_share',
                'unique_together': {('workspace_id', 'share_index')},
            },
        ),
    ]
