# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'users_login_session',
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('totp', 'TOTP (Authenticator App)'), ('fido2', 'FIDO2 / WebAuthn'), ('sms', 'SMS OTP'), ('hardware_key', 'USB Hardware Key'), ('backup', 'Backup Codes')], max_length=16)),
                ('name', models.CharField(help_text="User-visible label e.g. 'iPhone 15'", max_length=64)),
                ('secret_encrypted', models.TextField(help_text='AES-GCM encrypted TOTP secret or FIDO2 credential')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'users_mfa_device',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_encrypted', models.TextField(blank=True, help_text='AES-256-GCM encrypted phone')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('bio_encrypted', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en-US', max_length=16)),
                ('notification_prefs', models.JSONField(default=dict)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=16)),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='UserPublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('rsa_4096', 'RSA-4096'), ('ec_p384', 'ECDH P-384'), ('kyber_1024', 'Kyber-1024 (PQC KEM)'), ('ml_dsa_65', 'Dilithium3 (PQC Sig)')], max_length=16)),
                ('public_key_b64', models.TextField(help_text='Base64-encoded DER/raw key')),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_public_key',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Administrator'), ('compliance_officer', 'Compliance Officer'), ('branch_manager', 'Branch Manager'), ('senior_analyst', 'Senior Analyst'), ('analyst', 'Analyst'), ('trader', 'Trader'), ('support', 'Support Staff'), ('auditor', 'Auditor (Read-Only)'), ('external_counsel', 'External Counsel'), ('guest', 'Guest')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('permissions', models.JSONField(default=list, help_text='List of permission codenames')),
                ('max_clearance', models.PositiveSmallIntegerField(default=3)),
                ('can_access_vault', models.BooleanField(default=False)),
                ('can_export_messages', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('clearance_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='1=Basic, 5=Executive. Controls vault access.')),
                ('is_mfa_enforced', models.BooleanField(default=True)),
                ('is_mfa_verified', models.BooleanField(default=False)),
                ('pqc_public_key_kyber', models.TextField(blank=True, help_text='Kyber-1024 public key (base64)')),
                ('pqc_public_key_dilithium', models.TextField(blank=True, help_text='Dilithium3 verify key (base64)')),
                ('avatar_ipfs_cid', models.CharField(blank=True, max_length=128)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Admin/Axes hard lock')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Bank User',
                'verbose_name_plural': 'Bank Users',
                'db_table': 'users_bankuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('key_prefix', models.CharField(db_index=True, max_length=12)),
                ('key_hash', models.CharField(max_length=256, unique=True)),
                ('scopes', models.JSONField(default=list, help_text="e.g. ['read:messages', 'write:messages']")),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_api_key',
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=128)),
                ('device_label', models.CharField(blank=True, max_length=128)),
                ('trust_level', models.PositiveSmallIntegerField(choices=[(1, 'Partial'), (2, 'Full')], default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_device_fingerprint',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('employee_id', models.CharField(db_index=True, max_length=32)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('clearance_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='1=Basic, 5=Executive. Controls vault access.')),
                ('is_mfa_enforced', models.BooleanField(default=True)),
                ('is_mfa_verified', models.BooleanField(default=False)),
                ('pqc_public_key_kyber', models.TextField(blank=True, help_text='Kyber-1024 public key (base64)')),
                ('pqc_public_key_dilithium', models.TextField(blank=True, help_text='Dilithium3 verify key (base64)')),
                ('avatar_ipfs_cid', models.CharField(blank=True, max_length=128)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Admin/Axes hard lock')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Bank User',
                'verbose_name_plural': 'historical Bank Users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_invite_token',
            },
        ),
    ]
