# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpublickey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userrole'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Null = global role', null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddIndex(
            model_name='bankuser',
            index=models.Index(fields=['employee_id'], name='users_banku_employe_d26e15_idx'),
        ),
        migrations.AddIndex(
            model_name='bankuser',
            index=models.Index(fields=['clearance_level'], name='users_banku_clearan_325cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='bankuser',
            index=models.Index(fields=['last_active'], name='users_banku_last_ac_99d6f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicefingerprint',
            unique_together={('user', 'fingerprint_hash')},
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'is_revoked'], name='users_login_user_id_d02f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['expires_at'], name='users_login_expires_18538e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpublickey',
            unique_together={('user', 'key_type', 'is_current')},
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='users_role__user_id_8bc4ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together={('user', 'role', 'workspace')},
        ),
    ]
