# Generated by Django 6.0.1 on 2026-03-14 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_currencyrate_rbacpolicy_rbacpolicyassignment'),
        ('workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTimeRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_days', models.JSONField(default=list)),
                ('allowed_hours_start', models.TimeField()),
                ('allowed_hours_end', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_access_time_restriction',
            },
        ),
        migrations.CreateModel(
            name='BiometricAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biometric_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition'), ('voice', 'Voice Print'), ('iris', 'Iris Scan')], max_length=30)),
                ('template_hash', models.CharField(max_length=64)),
                ('encrypted_template_b64', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_biometric_auth',
            },
        ),
        migrations.CreateModel(
            name='DataClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], max_length=30)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('classified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'db_table': 'users_data_classification',
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('ip_range', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whitelists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to='workspace.workspace')),
            ],
            options={
                'db_table': 'users_ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(max_length=50, unique=True)),
                ('incident_type', models.CharField(choices=[('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('brute_force', 'Brute Force'), ('insider_threat', 'Insider Threat'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('remediation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_users', models.ManyToManyField(blank=True, related_name='security_incidents', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_security_incident',
            },
        ),
    ]
