# Generated by Django 6.0.1 on 2026-03-14 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_accesstimerestriction_biometricauth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOffboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('transfer', 'Transfer')], max_length=50)),
                ('access_revoked', models.BooleanField(default=False)),
                ('keys_rotated', models.BooleanField(default=False)),
                ('data_archived', models.BooleanField(default=False)),
                ('equipment_returned', models.BooleanField(default=False)),
                ('exit_interview_done', models.BooleanField(default=False)),
                ('last_day', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_offboardings', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_employee_offboarding',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('steps_completed', models.JSONField(default=list)),
                ('background_check_passed', models.BooleanField(default=False)),
                ('nda_signed', models.BooleanField(default=False)),
                ('security_training_done', models.BooleanField(default=False)),
                ('systems_access_granted', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_onboardings', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_employee_onboarding',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_type', models.CharField(choices=[('aml_awareness', 'AML Awareness'), ('data_privacy', 'Data Privacy'), ('cybersecurity', 'Cybersecurity'), ('code_of_conduct', 'Code of Conduct'), ('insider_trading', 'Insider Trading Policy'), ('gdpr', 'GDPR Compliance'), ('iso27001', 'ISO 27001')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_training_record',
            },
        ),
        migrations.CreateModel(
            name='VPNSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vpn_ip', models.GenericIPAddressField()),
                ('real_ip', models.GenericIPAddressField(null=True)),
                ('protocol', models.CharField(choices=[('wireguard', 'WireGuard'), ('openvpn', 'OpenVPN'), ('ipsec', 'IPSec')], default='wireguard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_vpn_session',
            },
        ),
        migrations.CreateModel(
            name='ZeroTrustPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_zero_trust_policy',
                'ordering': ['priority'],
            },
        ),
    ]
