# Generated by Django 6.0.1 on 2026-03-14 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employeeoffboarding_employeeonboarding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveAuthPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('auth_requirements', models.JSONField(default=list)),
                ('risk_threshold', models.FloatField(default=0.7)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('step_up_mfa', 'Step-Up MFA'), ('block', 'Block'), ('notify', 'Notify Only'), ('challenge', 'Challenge')], default='step_up_mfa', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_adaptive_auth_policy',
            },
        ),
        migrations.CreateModel(
            name='PrivilegedAccessManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=100)),
                ('access_type', models.CharField(choices=[('database', 'Database'), ('server', 'Server'), ('network', 'Network Device'), ('application', 'Application'), ('cloud', 'Cloud Console')], max_length=50)),
                ('justification', models.TextField()),
                ('session_recording_cid', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pam_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_pam_session',
            },
        ),
        migrations.CreateModel(
            name='SessionRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_factors', models.JSONField(default=dict)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_session_risk_score',
            },
        ),
    ]
