# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkspace',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('icon_ipfs_cid', models.CharField(blank=True, max_length=128)),
                ('compliance_region', models.CharField(choices=[('APAC', 'Asia-Pacific'), ('EMEA', 'Europe/Middle East/Africa'), ('AMER', 'Americas')], default='APAC', max_length=16)),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Message retention period')),
                ('is_e2ee_enforced', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical workspace',
                'verbose_name_plural': 'historical workspaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_ipfs_cid', models.CharField(blank=True, max_length=128)),
                ('compliance_region', models.CharField(choices=[('APAC', 'Asia-Pacific'), ('EMEA', 'Europe/Middle East/Africa'), ('AMER', 'Americas')], default='APAC', max_length=16)),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Message retention period')),
                ('is_e2ee_enforced', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('away', 'Away'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=16)),
                ('status_text', models.CharField(blank=True, max_length=100)),
                ('status_emoji', models.CharField(blank=True, max_length=32)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('dnd_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_user_presence',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('channel_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('dm', 'Direct Message'), ('group_dm', 'Group DM'), ('announcement', 'Announcement'), ('compliance', 'Compliance (Read-Only)')], default='public', max_length=16)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_read_only', models.BooleanField(default=False)),
                ('message_retention_override', models.PositiveIntegerField(blank=True, help_text='Days. Null = workspace default', null=True)),
                ('topic', models.CharField(blank=True, max_length=256)),
                ('purpose', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_channel',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userrole')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invites', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_invite',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('display_name_override', models.CharField(blank=True, max_length=64)),
                ('notification_level', models.CharField(choices=[('all', 'All'), ('mentions', 'Mentions Only'), ('none', 'None')], default='all', max_length=16)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_member',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_guest_access', models.BooleanField(default=False)),
                ('require_mfa_for_all', models.BooleanField(default=True)),
                ('allowed_file_types', models.JSONField(default=list, help_text='e.g. ["pdf","docx"]')),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=25)),
                ('enable_message_editing', models.BooleanField(default=True)),
                ('editing_window_seconds', models.PositiveIntegerField(default=300, help_text='0 = disable editing after send')),
                ('enable_link_preview', models.BooleanField(default=False, help_text='Disabled by default — security')),
                ('screenshot_protection', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_settings',
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('is_muted', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace.channel')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_channel_member',
                'indexes': [models.Index(fields=['user', 'channel'], name='workspace_c_user_id_09e239_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='workspace.channel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='messaging.message')),
                ('pinned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_channel_pin',
                'unique_together': {('channel', 'message')},
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('ipfs_cid', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_emojis', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_emoji',
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['workspace', 'channel_type', 'is_archived'], name='workspace_c_workspa_ed121f_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['last_activity'], name='workspace_c_last_ac_1d70f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('workspace', 'slug')},
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'status'], name='workspace_m_workspa_17ef29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'user')},
        ),
    ]
