# Generated by Django 6.0.1 on 2026-03-14 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_category', models.CharField(choices=[('trading_desk', 'Trading Desk'), ('risk_management', 'Risk Management'), ('compliance', 'Compliance'), ('treasury', 'Treasury'), ('retail_banking', 'Retail Banking'), ('corporate_banking', 'Corporate Banking'), ('investment', 'Investment Banking'), ('swift_ops', 'SWIFT Operations')], max_length=50)),
                ('requires_compliance_review', models.BooleanField(default=False)),
                ('max_message_ttl', models.PositiveIntegerField(default=86400)),
                ('requires_mfa', models.BooleanField(default=True)),
                ('min_clearance_level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_config', to='workspace.channel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_channels', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_banking_channel',
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_type', models.CharField(choices=[('pre_trade', 'Pre-Trade Check'), ('post_trade', 'Post-Trade Check'), ('communication', 'Communication Review'), ('document', 'Document Approval')], max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('approver_role', models.CharField(blank=True, max_length=50)),
                ('sla_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='workspace.channel')),
            ],
            options={
                'db_table': 'workspace_compliance_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='DealRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deal_type', models.CharField(choices=[('ma', 'Mergers & Acquisitions'), ('loan', 'Loan Syndication'), ('ipo', 'IPO'), ('bond', 'Bond Issuance'), ('fx', 'FX Deal')], max_length=50)),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('nda_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='deal_rooms', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_rooms', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_deal_room',
            },
        ),
        migrations.CreateModel(
            name='MessageApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.compliancecheckpoint')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_message_approval',
            },
        ),
    ]
