# Generated by Django 6.0.1 on 2026-03-14 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('sla_minutes_l1', models.PositiveIntegerField(default=30)),
                ('sla_minutes_l2', models.PositiveIntegerField(default=60)),
                ('sla_minutes_l3', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_l1', to=settings.AUTH_USER_MODEL)),
                ('level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_l2', to=settings.AUTH_USER_MODEL)),
                ('level_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_l3', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_matrix', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_escalation_matrix',
            },
        ),
        migrations.CreateModel(
            name='TradingDesk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desk_type', models.CharField(choices=[('equity', 'Equity'), ('fixed_income', 'Fixed Income'), ('fx', 'Foreign Exchange'), ('derivatives', 'Derivatives'), ('commodities', 'Commodities'), ('crypto', 'Digital Assets')], max_length=50)),
                ('risk_limit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('daily_var_limit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_desks', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='trading_desks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_desks', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_trading_desk',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ciphertext_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_announcement',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('bloomberg', 'Bloomberg Terminal'), ('reuters', 'Reuters Eikon'), ('swift', 'SWIFT Alliance'), ('murex', 'Murex'), ('calypso', 'Calypso'), ('temenos', 'Temenos'), ('fiserv', 'Fiserv')], max_length=50)),
                ('api_endpoint', models.URLField(blank=True)),
                ('encrypted_credentials_b64', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_integration',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='workspace.workspaceannouncement')),
            ],
            options={
                'db_table': 'workspace_announcement_ack',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
