# Generated by Django 6.0.1 on 2026-03-14 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_escalationmatrix_tradingdesk_workspaceannouncement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLevelAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('uptime', 'Uptime'), ('transaction_speed', 'Transaction Speed'), ('resolution_time', 'Resolution Time')], max_length=50)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0.0)),
                ('unit', models.CharField(max_length=20)),
                ('is_breached', models.BooleanField(default=False)),
                ('breach_count', models.PositiveIntegerField(default=0)),
                ('last_measured', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_sla',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=50)),
                ('reference_type', models.CharField(max_length=50)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('action_taken', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('returned', 'Returned'), ('skipped', 'Skipped')], max_length=50)),
                ('comments_encrypted_b64', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workspace.workflowinstance')),
            ],
            options={
                'db_table': 'workspace_workflow_step',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('workflow_type', models.CharField(choices=[('loan_approval', 'Loan Approval'), ('account_opening', 'Account Opening'), ('kyc_review', 'KYC Review'), ('trade_approval', 'Trade Approval'), ('complaint_handling', 'Complaint Handling'), ('fraud_investigation', 'Fraud Investigation'), ('contract_signing', 'Contract Signing')], max_length=50)),
                ('steps', models.JSONField(default=list)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_workflow_template',
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workspace.workflowtemplate'),
        ),
    ]
