# Generated by Django 6.0.1 on 2026-03-14 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_servicelevelagreement_workflowinstance_workflowstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(choices=[('commercial_bank', 'Commercial Bank'), ('investment_bank', 'Investment Bank'), ('digital_bank', 'Digital Bank'), ('payment_institution', 'Payment Institution'), ('securities_firm', 'Securities Firm'), ('asset_management', 'Asset Management')], max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('issuing_authority', models.CharField(choices=[('ojk', 'OJK'), ('bi', 'Bank Indonesia'), ('bappebti', 'BAPPEBTI'), ('sec', 'SEC')], max_length=50)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('document_cid', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_banking_license',
            },
        ),
        migrations.CreateModel(
            name='BoardResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('resolution_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('document_cid', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signatories', models.ManyToManyField(related_name='board_resolutions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_resolutions', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_board_resolution',
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=20, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_type', models.CharField(choices=[('head_office', 'Head Office'), ('regional', 'Regional Office'), ('branch', 'Branch'), ('sub_branch', 'Sub Branch'), ('atm', 'ATM'), ('digital', 'Digital Branch')], max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Indonesia', max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_branches', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_branch_office',
            },
        ),
        migrations.CreateModel(
            name='CorporateHierarchy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('holding', 'Holding Company'), ('subsidiary', 'Subsidiary'), ('affiliate', 'Affiliate'), ('joint_venture', 'Joint Venture'), ('special_purpose', 'Special Purpose Vehicle')], max_length=50)),
                ('ownership_percentage', models.FloatField(default=100.0)),
                ('country', models.CharField(max_length=50)),
                ('is_regulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workspace.corporatehierarchy')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_corporate_hierarchy',
            },
        ),
    ]
