# Generated by Django 6.0.1 on 2026-03-15 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_budgettracker_budgetexpense_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('message_sent', 'Message Sent'), ('member_joined', 'Member Joined'), ('due_date', 'Due Date Reached')], max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_automation',
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_data', models.JSONField(default=dict)),
                ('actions_taken', models.JSONField(default=list)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workspace.automation')),
            ],
            options={
                'db_table': 'workspace_automation_log',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('url', 'URL'), ('email', 'Email')], max_length=20)),
                ('options', models.JSONField(default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('apply_to', models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('user', 'User')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_custom_field',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='workspace.customfield')),
            ],
            options={
                'db_table': 'workspace_custom_field_value',
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('messages', 'Messages'), ('files', 'Files'), ('tasks', 'Tasks'), ('users', 'Users'), ('full', 'Full Workspace')], max_length=50)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('zip', 'ZIP')], max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file_cid', models.TextField(blank=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_data_export',
            },
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('notion', 'Notion'), ('jira', 'Jira'), ('csv', 'CSV'), ('json', 'JSON')], max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('imported_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_data_import',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(max_length=50)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_triggers', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_workflow_trigger',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('app_type', models.CharField(choices=[('bot', 'Bot'), ('integration', 'Integration'), ('webhook', 'Webhook'), ('slash_command', 'Slash Command')], max_length=50)),
                ('app_url', models.URLField(blank=True)),
                ('token_encrypted_b64', models.TextField(blank=True)),
                ('nonce_b64', models.TextField(blank=True)),
                ('auth_tag_b64', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_app',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('background_color', models.CharField(default='#0a0a0f', max_length=7)),
                ('sidebar_color', models.CharField(default='#1a1d21', max_length=7)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_theme',
            },
        ),
        migrations.CreateModel(
            name='SlashCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slash_commands', to='workspace.workspace')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='workspace.workspaceapp')),
            ],
            options={
                'db_table': 'workspace_slash_command',
                'unique_together': {('workspace', 'command')},
            },
        ),
    ]
