# Generated by Django 6.0.1 on 2026-03-15 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_accountingentry_budget_currencyrate_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('hypothesis', models.TextField()),
                ('variants', models.JSONField(default=list)),
                ('metric', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('winner', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_abtest',
            },
        ),
        migrations.CreateModel(
            name='APIMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time_ms', models.PositiveIntegerField()),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_metric',
            },
        ),
        migrations.CreateModel(
            name='CIBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('repo', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_ci_build',
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.JSONField(default=dict)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_cohort',
            },
        ),
        migrations.CreateModel(
            name='CustomDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dimension_type', models.CharField(choices=[('user', 'User'), ('session', 'Session'), ('event', 'Event')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_dimension',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('metric', 'Metric'), ('list', 'List'), ('map', 'Map')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=4)),
                ('height', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_widget',
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('database_name', models.CharField(max_length=100)),
                ('size_mb', models.PositiveIntegerField(default=0)),
                ('storage_cid', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=20)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_backup',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('success', 'Success'), ('failed', 'Failed'), ('rollback', 'Rollback')], max_length=20)),
                ('deployed_by', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('logs', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'devops_deployment',
            },
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=100)),
                ('size_mb', models.PositiveIntegerField(default=0)),
                ('digest', models.CharField(blank=True, max_length=100)),
                ('pushed_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_image',
            },
        ),
        migrations.CreateModel(
            name='ErrorTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('service', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'devops_error',
            },
        ),
        migrations.CreateModel(
            name='EventTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('workspace_id', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_event',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percent', models.PositiveSmallIntegerField(default=0)),
                ('environments', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_flag',
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('funnel_name', models.CharField(max_length=100)),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('users_entered', models.PositiveIntegerField(default=0)),
                ('users_completed', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'analytics_funnel',
            },
        ),
        migrations.CreateModel(
            name='GoalTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('goal_name', models.CharField(max_length=100)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('deadline', models.DateField(null=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_goal',
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('page_path', models.CharField(max_length=255)),
                ('click_x', models.PositiveSmallIntegerField()),
                ('click_y', models.PositiveSmallIntegerField()),
                ('element', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_heatmap',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_cost',
            },
        ),
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('aws', 'AWS EKS'), ('gcp', 'GCP GKE'), ('azure', 'Azure AKS'), ('self', 'Self-hosted')], max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('node_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_k8s',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('trace', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_log',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('tags', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_metric',
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_alert',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=50)),
                ('filters', models.JSONField(default=dict)),
                ('schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('last_run', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_report',
            },
        ),
        migrations.CreateModel(
            name='RetentionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('cohort_date', models.DateField()),
                ('period', models.PositiveSmallIntegerField()),
                ('users', models.PositiveIntegerField(default=0)),
                ('retained', models.PositiveIntegerField(default=0)),
                ('retention_rate', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'analytics_retention',
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_search',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('server_type', models.CharField(choices=[('web', 'Web'), ('db', 'Database'), ('cache', 'Cache'), ('queue', 'Queue'), ('storage', 'Storage'), ('cdn', 'CDN')], max_length=20)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('cpu_cores', models.PositiveSmallIntegerField(default=1)),
                ('ram_gb', models.PositiveSmallIntegerField(default=1)),
                ('disk_gb', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_server',
            },
        ),
        migrations.CreateModel(
            name='ServiceHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('uptime_percent', models.FloatField(default=100.0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_health',
            },
        ),
        migrations.CreateModel(
            name='SLAReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=20)),
                ('uptime_percent', models.FloatField()),
                ('avg_response_ms', models.FloatField()),
                ('incidents', models.PositiveSmallIntegerField(default=0)),
                ('sla_met', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_sla',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('workspace_id', models.CharField(max_length=50)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_session',
            },
        ),
        migrations.CreateModel(
            name='K8sPod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(default='default', max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_mb', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='workspace.k8scluster')),
            ],
            options={
                'db_table': 'devops_pod',
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('file_cid', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workspace.report')),
            ],
            options={
                'db_table': 'analytics_run',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='workspace.usersession')),
            ],
            options={
                'db_table': 'analytics_pageview',
            },
        ),
    ]
