# Generated by Django 6.0.1 on 2026-03-15 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_abtest_apimetric_cibuild_cohort_customdimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_policy',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_trail',
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField(blank=True)),
                ('blocked_by', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_blocked_ip',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50, unique=True)),
                ('logo_cid', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('font_primary', models.CharField(default='Inter', max_length=50)),
                ('font_secondary', models.CharField(default='Inter', max_length=50)),
                ('guidelines_cid', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_brand',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('image', 'Image'), ('code', 'Code'), ('table', 'Table'), ('divider', 'Divider'), ('callout', 'Callout')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_block',
            },
        ),
        migrations.CreateModel(
            name='DataClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('secret', 'Secret'), ('top_secret', 'Top Secret')], max_length=20)),
                ('classified_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_classification',
            },
        ),
        migrations.CreateModel(
            name='DiagramCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('diagram_type', models.CharField(choices=[('flowchart', 'Flowchart'), ('er', 'ER Diagram'), ('sequence', 'Sequence'), ('mindmap', 'Mind Map'), ('org', 'Org Chart')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_diagram',
            },
        ),
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('fields', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_form',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_login',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('ipfs_cid', models.TextField(blank=True)),
                ('thumbnail_cid', models.TextField(blank=True)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_file',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_tag',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('manage', 'Manage')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_permission',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('slides', models.JSONField(default=list)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_presentation',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('permissions', models.JSONField(default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_role',
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('affected_users', models.JSONField(default=list)),
                ('status', models.CharField(default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_incident',
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50, unique=True)),
                ('min_password_length', models.PositiveSmallIntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('require_symbols', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveSmallIntegerField(default=90)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(default=60)),
                ('require_mfa', models.BooleanField(default=False)),
                ('ip_whitelist', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sec_security_policy',
            },
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('sheets', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_spreadsheet',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_survey',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('blocks', models.JSONField(default=list)),
                ('thumbnail_cid', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_template',
            },
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('thumbnail_cid', models.TextField(blank=True)),
                ('collaborators', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_whiteboard',
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_id', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workspace.formbuilder')),
            ],
            options={
                'db_table': 'media_form_response',
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='workspace.mediafolder')),
            ],
            options={
                'db_table': 'media_folder',
            },
        ),
        migrations.CreateModel(
            name='MediaShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_by', models.CharField(max_length=50)),
                ('shared_with', models.CharField(blank=True, max_length=50)),
                ('share_link', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='workspace.mediafile')),
            ],
            options={
                'db_table': 'media_share',
            },
        ),
        migrations.CreateModel(
            name='MediaFileTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspace.mediafile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.mediatag')),
            ],
            options={
                'db_table': 'media_file_tag',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('assigned_by', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.role')),
            ],
            options={
                'db_table': 'sec_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_id', models.CharField(blank=True, max_length=50)),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workspace.survey')),
            ],
            options={
                'db_table': 'media_survey_response',
            },
        ),
    ]
