# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateIDVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name_enc', models.TextField()),
                ('registration_number_enc', models.TextField()),
                ('registration_country_enc', models.TextField()),
                ('registration_date_enc', models.TextField()),
                ('registered_address_enc', models.TextField()),
                ('tax_number_enc', models.TextField(blank=True)),
                ('authorised_signatories_enc', models.TextField(help_text='Encrypted JSON array')),
                ('certificate_of_incorporation_cid', models.CharField(blank=True, max_length=128)),
                ('memorandum_of_association_cid', models.CharField(blank=True, max_length=128)),
                ('board_resolution_cid', models.CharField(blank=True, max_length=128)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('under_review', 'Under Review')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_version', models.PositiveSmallIntegerField(default=1)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_verifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_vault', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Corporate ID Vault',
                'db_table': 'vault_corporate_id',
            },
        ),
        migrations.CreateModel(
            name='HardwareKeyRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'Primary Key'), (2, 'Backup Key')])),
                ('key_type', models.CharField(choices=[('fido2_yubikey', 'FIDO2 YubiKey'), ('fido2_generic', 'FIDO2 Generic'), ('piv_smart_card', 'PIV Smart Card'), ('pkcs11_token', 'PKCS#11 Token')], max_length=16)),
                ('label', models.CharField(help_text="User-visible label e.g. 'YubiKey 5C NFC'", max_length=64)),
                ('credential_id_enc', models.TextField(help_text='Encrypted FIDO2 credential ID')),
                ('public_key_enc', models.TextField(help_text='Encrypted COSE public key')),
                ('aaguid', models.CharField(blank=True, help_text='Authenticator AAGUID', max_length=64)),
                ('vendor_id', models.CharField(blank=True, help_text='USB Vendor ID hex e.g. 0x1050', max_length=8)),
                ('product_id', models.CharField(blank=True, help_text='USB Product ID hex e.g. 0x0407', max_length=8)),
                ('serial_number_enc', models.TextField(blank=True, help_text='Encrypted device serial number')),
                ('sign_count', models.PositiveBigIntegerField(default=0, help_text='FIDO2 signature counter — detects cloning')),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hardware Key Registry',
                'db_table': 'vault_hardware_key',
            },
        ),
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(db_index=True, max_length=256, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('fido2_challenge_b64', models.TextField(blank=True)),
                ('fido2_assertion_b64', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_reason', models.CharField(blank=True, max_length=64)),
                ('action_log', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_sessions', to=settings.AUTH_USER_MODEL)),
                ('hardware_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_sessions', to='vault.hardwarekeyregistry')),
            ],
            options={
                'verbose_name': 'Vault Access Session',
                'db_table': 'vault_access_session',
            },
        ),
        migrations.CreateModel(
            name='UserKYCVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_enc', models.TextField(help_text='Encrypted legal full name')),
                ('date_of_birth_enc', models.TextField(help_text='Encrypted DOB (ISO format)')),
                ('nationality_enc', models.TextField(help_text='Encrypted nationality code')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License')], max_length=16)),
                ('id_number_enc', models.TextField(help_text='Encrypted ID number')),
                ('id_expiry_enc', models.TextField(help_text='Encrypted expiry date')),
                ('id_document_ipfs_cid', models.CharField(blank=True, help_text='Encrypted scan stored on IPFS', max_length=128)),
                ('address_enc', models.TextField(blank=True, help_text='Encrypted residential address')),
                ('tax_id_enc', models.TextField(blank=True, help_text='Encrypted tax identification number')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_version', models.PositiveSmallIntegerField(default=1, help_text='AES key rotation version')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_vault', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Vault Record',
                'db_table': 'vault_kyc',
            },
        ),
        migrations.CreateModel(
            name='EncryptedBlobStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blob_type', models.CharField(choices=[('document', 'Document'), ('certificate', 'Certificate'), ('evidence', 'Audit Evidence'), ('secure_note', 'Secure Note'), ('key_backup', 'Key Backup')], max_length=16)),
                ('label', models.CharField(max_length=128)),
                ('description_enc', models.TextField(blank=True, help_text='Encrypted description')),
                ('ipfs_cid', models.CharField(db_index=True, help_text='IPFS CID of encrypted blob', max_length=128)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('blob_key_enc', models.TextField(help_text="Blob AES key, encrypted with owner's Kyber public key")),
                ('blob_nonce_b64', models.CharField(max_length=32)),
                ('blob_tag_b64', models.CharField(max_length=32)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('min_clearance', models.PositiveSmallIntegerField(default=3)),
                ('ttl_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('destroy_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_version', models.PositiveSmallIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_blobs', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_vault_blobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_blobs', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Encrypted Blob Store',
                'db_table': 'vault_blob_store',
                'indexes': [models.Index(fields=['owner', 'blob_type'], name='vault_blob__owner_i_4da7d7_idx'), models.Index(fields=['destroy_at'], name='vault_blob__destroy_672b17_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hardwarekeyregistry',
            index=models.Index(fields=['user', 'is_active'], name='vault_hardw_user_id_cf3d90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hardwarekeyregistry',
            unique_together={('user', 'slot')},
        ),
        migrations.AddIndex(
            model_name='accesssession',
            index=models.Index(fields=['user', 'is_active'], name='vault_acces_user_id_79d618_idx'),
        ),
        migrations.AddIndex(
            model_name='accesssession',
            index=models.Index(fields=['expires_at'], name='vault_acces_expires_3d74fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userkycvault',
            index=models.Index(fields=['kyc_status'], name='vault_kyc_kyc_sta_69b735_idx'),
        ),
        migrations.AddIndex(
            model_name='userkycvault',
            index=models.Index(fields=['verified_at'], name='vault_kyc_verifie_58a71b_idx'),
        ),
    ]
