# Generated by Django 6.0.1 on 2026-03-14 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKeyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('key_fingerprint', models.CharField(max_length=64)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vault_master_key_version',
            },
        ),
        migrations.CreateModel(
            name='KeyAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_key_access_log',
            },
        ),
        migrations.CreateModel(
            name='KeyDerivationParams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salt_b64', models.TextField()),
                ('info_b64', models.TextField()),
                ('algorithm', models.CharField(default='HKDF-SHA512', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_params', to='workspace.channel')),
            ],
            options={
                'db_table': 'vault_key_derivation_params',
            },
        ),
        migrations.CreateModel(
            name='KeyEscrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(max_length=50)),
                ('encrypted_key_b64', models.TextField()),
                ('escrow_nonce_b64', models.TextField()),
                ('escrow_tag_b64', models.TextField()),
                ('custodian', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_escrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_key_escrow',
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(max_length=50)),
                ('old_key_fingerprint', models.CharField(max_length=64)),
                ('new_key_fingerprint', models.CharField(max_length=64)),
                ('reason', models.CharField(default='scheduled', max_length=100)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_key_rotation_log',
            },
        ),
    ]
