# Generated by Django 6.0.1 on 2026-03-14 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_masterkeyversion_keyaccesslog_keyderivationparams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SWIFTMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=10)),
                ('sender_bic', models.CharField(max_length=11)),
                ('receiver_bic', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('encrypted_payload_b64', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vault_swift_message',
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_hash', models.CharField(max_length=64)),
                ('document_name', models.CharField(max_length=255)),
                ('document_cid', models.TextField(blank=True)),
                ('signature_b64', models.TextField()),
                ('signature_algorithm', models.CharField(default='Dilithium3', max_length=50)),
                ('public_key_fingerprint', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_document_signature',
            },
        ),
        migrations.CreateModel(
            name='MultiPartySignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_hash', models.CharField(max_length=64)),
                ('document_name', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_signatures', models.ManyToManyField(related_name='multi_party', to='vault.documentsignature')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('required_signers', models.ManyToManyField(related_name='pending_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_multi_party_signature',
            },
        ),
    ]
