# Generated by Django 6.0.1 on 2026-03-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_swiftmessage_documentsignature_multipartysignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSMKeySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_id', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('key_type', models.CharField(choices=[('rsa_4096', 'RSA-4096'), ('ecdsa_p384', 'ECDSA-P384'), ('aes_256', 'AES-256'), ('kyber_1024', 'Kyber-1024'), ('ml_dsa_65', 'Dilithium3')], max_length=50)),
                ('key_fingerprint', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.BigIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vault_hsm_key_slot',
            },
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('certificate_pem', models.TextField()),
                ('public_key_b64', models.TextField()),
                ('is_root', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.certificateauthority')),
            ],
            options={
                'db_table': 'vault_certificate_authority',
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('certificate_pem', models.TextField()),
                ('public_key_b64', models.TextField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certs', to='vault.certificateauthority')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_issued_certificate',
            },
        ),
        migrations.CreateModel(
            name='SecureEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_encrypted_b64', models.TextField()),
                ('content_cid', models.TextField()),
                ('kyber_ciphertext_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('dilithium_signature_b64', models.TextField(blank=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('destroy_after_read', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_envelopes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_envelopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_secure_envelope',
            },
        ),
        migrations.CreateModel(
            name='TokenVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('data_type', models.CharField(choices=[('card_number', 'Card Number'), ('account_number', 'Account Number'), ('swift_bic', 'SWIFT BIC'), ('iban', 'IBAN'), ('ssn', 'SSN/NIK')], max_length=50)),
                ('encrypted_value_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_token',
            },
        ),
    ]
