# Generated by Django 6.0.1 on 2026-03-14 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_hsmkeyslot_certificateauthority_issuedcertificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterRecoveryPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('bcp', 'Business Continuity Plan'), ('drp', 'Disaster Recovery Plan'), ('irp', 'Incident Response Plan'), ('crisis', 'Crisis Management')], max_length=50)),
                ('rto_minutes', models.PositiveIntegerField(default=60)),
                ('rpo_minutes', models.PositiveIntegerField(default=30)),
                ('steps', models.JSONField(default=list)),
                ('contacts', models.JSONField(default=list)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('next_test', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_disaster_recovery',
            },
        ),
        migrations.CreateModel(
            name='SecureNotepad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_encrypted_b64', models.TextField()),
                ('content_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('category', models.CharField(choices=[('credentials', 'Credentials'), ('meeting_notes', 'Meeting Notes'), ('deal_notes', 'Deal Notes'), ('personal', 'Personal'), ('compliance', 'Compliance')], default='personal', max_length=50)),
                ('is_pinned', models.BooleanField(default=False)),
                ('destroy_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_secure_notepad',
            },
        ),
        migrations.CreateModel(
            name='SecureSharing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('max_access_count', models.PositiveIntegerField(default=1)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('requires_mfa', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_secure_sharing',
            },
        ),
        migrations.CreateModel(
            name='VaultAccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('kyc', 'KYC Records'), ('blob', 'Blob Store'), ('signature', 'Digital Signatures'), ('certificate', 'Certificates'), ('token', 'Token Vault'), ('notepad', 'Secure Notepad')], max_length=50)),
                ('allowed_roles', models.JSONField(default=list)),
                ('min_clearance', models.PositiveSmallIntegerField(default=1)),
                ('requires_mfa', models.BooleanField(default=True)),
                ('requires_hardware_key', models.BooleanField(default=False)),
                ('time_restrictions', models.JSONField(default=dict)),
                ('ip_restrictions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_access_policy',
            },
        ),
    ]
