# Generated by Django 6.0.1 on 2026-03-14 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_disasterrecoveryplan_securenotepad_securesharing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBDCTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('currency', models.CharField(default='e-IDR', max_length=10)),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('block_number', models.BigIntegerField(null=True)),
                ('smart_contract_address', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbdc_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbdc_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_cbdc_transaction',
            },
        ),
        migrations.CreateModel(
            name='DigitalAssetCustody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cbdc', 'CBDC'), ('stablecoin', 'Stablecoin'), ('tokenized_asset', 'Tokenized Asset')], max_length=50)),
                ('wallet_address_encrypted_b64', models.TextField()),
                ('private_key_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('is_cold_storage', models.BooleanField(default=True)),
                ('custodian', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_digital_asset',
            },
        ),
        migrations.CreateModel(
            name='SmartContractAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_address', models.CharField(max_length=100)),
                ('contract_name', models.CharField(max_length=100)),
                ('audit_type', models.CharField(choices=[('security', 'Security Audit'), ('compliance', 'Compliance Audit'), ('functional', 'Functional Audit')], max_length=50)),
                ('vulnerabilities_found', models.PositiveIntegerField(default=0)),
                ('critical_issues', models.PositiveIntegerField(default=0)),
                ('audit_report_cid', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_smart_contract_audit',
            },
        ),
    ]
