# Generated by Django 6.0.1 on 2026-03-15 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_postquantummigration_quantumkeydistribution'),
        ('workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('key_name', models.CharField(max_length=100)),
                ('api_key_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], default='development', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys_vault', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_api_key',
            },
        ),
        migrations.CreateModel(
            name='PasswordVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('username_encrypted_b64', models.TextField()),
                ('password_encrypted_b64', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('notes_encrypted_b64', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('social', 'Social'), ('finance', 'Finance'), ('other', 'Other')], default='work', max_length=50)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_password',
            },
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('private_key_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('key_type', models.CharField(choices=[('rsa', 'RSA'), ('ed25519', 'Ed25519'), ('ecdsa', 'ECDSA')], default='ed25519', max_length=20)),
                ('passphrase_hint', models.CharField(blank=True, max_length=100)),
                ('servers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_ssh_key',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('value_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_secrets', to='workspace.workspace')),
            ],
            options={
                'db_table': 'vault_env_secret',
                'unique_together': {('workspace', 'key_name', 'environment')},
            },
        ),
    ]
