# Generated by Django 6.0.1 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_apikeyvault_passwordvault_sshkey_environmentsecret'),
        ('workspace', '0009_budgettracker_budgetexpense_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value_encrypted_b64', models.TextField()),
                ('nonce_b64', models.TextField()),
                ('auth_tag_b64', models.TextField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_secrets_access', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_secrets', to='workspace.workspace')),
            ],
            options={
                'db_table': 'vault_shared_secret',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_token_hash', models.CharField(max_length=64, unique=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_trusted_device',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_2fa_backup_code',
            },
        ),
        migrations.CreateModel(
            name='VaultAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_audit',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('messages', 'Messages Only'), ('files', 'Files Only')], max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('storage_cid', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='workspace.workspace')),
            ],
            options={
                'db_table': 'vault_workspace_backup',
            },
        ),
    ]
